---
- name: restart_chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: restart_nova
  ansible.builtin.service:
    name: nova-compute
    state: restarted

- name: restart_neutron
  ansible.builtin.service:
    name: neutron-openvswitch-agent
    state: restarted
