---
- name: restart_chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: restart_memcached
  ansible.builtin.service:
    name: memcached
    state: restarted

- name: restart_etcd
  ansible.builtin.service:
    name: etcd
    state: restarted

- name: restart_apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
