---
- name: restart_chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: restart_memcached
  ansible.builtin.service:
    name: memcached
    state: restarted

- name: restart_etcd
  ansible.builtin.service:
    name: etcd
    state: restarted

- name: restart_apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: reload_apache2
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: restart_glance_api
  ansible.builtin.service:
    name: glance-api
    state: restarted

- name: restart_nova
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy

- name: restart_neutron
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - neutron-server
    - neutron-openvswitch-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    
- name: restart_cinder
  ansible.builtin.service:
    name: cinder-scheduler
    state: restarted
