---
- name: create_user
  community.mysql.mysql_user:
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
    name: "{{ outer_item['user'] }}"
    host: "{{ item }}"
    password: "{{ outer_item['pass'] }}"
    priv: "{{ outer_item['db'] }}.*:ALL"
  loop:
    - localhost
    - "%"
