---
- name: install_database
  ansible.builtin.apt:
    name: mariadb-server

- name: start_database
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true 

- name: install_python_mysql_package
  ansible.builtin.apt:
    name: python3-pymysql

- name: put_config
  ansible.builtin.template:
    src: ./99-openstack.cnf.j2
    dest:  /etc/mysql/mariadb.conf.d/99-openstack.cnf 
    owner: root
    group: root
    mode: '644'
  notify: restart_database

- name: secure_installation
  ansible.builtin.include_tasks:
    file: secure_installation.yml
