---
# NOTE: This is in still under construction. Don't use!
- name: set_root_pass
  community.mysql.mysql_user:
      login_user: root
      login_unix_socket: /run/mysqld/mysqld.sock
      name: root
      host_all: true
      password: "{{ database_root_pass }}"
- name: disable_remote_root_login
  community.mysql.mysql_user:
      login_user: root
      login_unix_socket: /run/mysqld/mysqld.sock
      name: root
      host: "{{ ansible_fqdn | lower }}"
      state: absent
- name: remove_anonymous_users
  community.mysql.mysql_user:
      login_user: root
      login_unix_socket: /run/mysqld/mysqld.sock
      name: ''
      host_all: true
      state: absent
- name: remove_test_database
  mysql_db: 
      login_user: root
      login_unix_socket: /run/mysqld/mysqld.sock
      db: test
      state: absent
