---
- name: set_root_pass
  mysql_user:
      login_user: root
      login_password: ""
      user: root
      host_all: true
      password: "{{ database_root_pass }}"
- name: disable_remote_root_login
  mysql_user:
      login_user: root
      login_password: "{{ database_root_pass }}"
      user: root
      host: "{{ ansible_fqdn | lower }}"
      state: absent
- name: remove_anonymous_users
  mysql_user:
      login_user: root
      login_password: "{{ database_root_pass }}"
      user: ''
      host_all: true
      state: absent
- name: remove_test_database
  mysql_db: 
      login_user: root
      login_password: "{{ database_root_pass }}"
      db: test
      state: absent
  register: remove_testdb
- name: remove_test_database_priviledges
  block:
    - shell: >
        mysql -u root -p{{ database_root_pass }} 
        -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
    - shell: mysql -u root -p{{ database_root_pass }} -e "FLUSH PRIVILEGES"
  when: remove_testdb.changed
