---
- name: install_keystone
  ansible.builtin.apt:
    name: keystone

- name: put_keystone_config
  ansible.builtin.template:
    src: ./keystone.conf.j2
    dest:  /etc/keystone/keystone.conf
    owner: root
    group: root
    mode: '644'

- name: check_db_sync
  ansible.builtin.command:
    cmd: keystone-manage db_sync --check
  register: check_db_sync
  failed_when: check_db_sync.rc == 1
  changed_when: check_db_sync.rc != 0
  run_once: true

- name: run_db_sync
  ansible.builtin.command:
    cmd: su -s /bin/sh -c "keystone-manage db_sync" keystone
  when: check_db_sync.changed
  run_once: true

- name: run_fernet_setup
  ansible.builtin.command:
    cmd: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
  when: check_db_sync.changed
  run_once: true

- name: run_credential_setup
  ansible.builtin.command:
    cmd: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  when: check_db_sync.changed
  run_once: true

- name: run_bootstrap
  ansible.builtin.command:
    cmd: >
      keystone-manage bootstrap --bootstrap-password "{{ openstack_admin_pass }}"
        --bootstrap-admin-url http://controller:5000/v3/
        --bootstrap-internal-url http://controller:5000/v3/
        --bootstrap-public-url http://controller:5000/v3/
        --bootstrap-region-id RegionOne
  changed_when: false
  run_once: true

- name: put_apache2_config
  ansible.builtin.template:
    src: ./apache2.conf.j2
    dest:  /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: '644'
  notify: restart_apache2
