---
- name: setup_ntp
  ansible.builtin.include_tasks:
    file: ntp.yml

- name: setup_rabbitmq
  ansible.builtin.include_tasks:
    file: rabbitmq.yml

- name: setup_memcached
  ansible.builtin.include_tasks:
    file: memcached.yml

- name: setup_etcd
  ansible.builtin.include_tasks:
    file: etcd.yml
