---
- name: setup_ntp
  ansible.builtin.include_tasks:
    file: ntp.yml

- name: setup_rabbitmq
  ansible.builtin.include_tasks:
    file: rabbitmq.yml

- name: setup_memcached
  ansible.builtin.include_tasks:
    file: memcached.yml

- name: setup_etcd
  ansible.builtin.include_tasks:
    file: etcd.yml

- name: setup_keystone
  ansible.builtin.include_tasks:
    file: keystone.yml

- name: setup_glance
  ansible.builtin.include_tasks:
    file: glance.yml

- name: setup_placement
  ansible.builtin.include_tasks:
    file: placement.yml

- name: setup_nova
  ansible.builtin.include_tasks:
    file: nova.yml

- name: setup_neutron
  ansible.builtin.include_tasks:
    file: neutron.yml
