---
- name: install_chrony
  ansible.builtin.apt:
    name: chrony

- name: start_chrony
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true

- name: pub_chrony_config
  ansible.builtin.template:
    src: ./chrony.conf.j2
    dest:  /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '644'
  notify: restart_chrony
