---
- name: install_rabbitmq
  ansible.builtin.apt:
    name: rabbitmq-server

- name: start_rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: create_openstack_user
  community.rabbitmq.rabbitmq_user:
    user: openstack
    password: "{{ rabbitmq_pass }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
  run_once: true
