---
- name: setup_ntp
  ansible.builtin.include_tasks:
    file: ntp.yml

- name: setup_nova
  ansible.builtin.include_tasks:
    file: nova.yml

- name: setup_neutron
  ansible.builtin.include_tasks:
    file: neutron.yml
