---
- name: install_neutron_ovs_agent
  ansible.builtin.apt:
    name: neutron-openvswitch-agent

- name: create_br_provider
  openvswitch.openvswitch.openvswitch_bridge:
    bridge: br-provider
    fail_mode: secure

- name: create_br_provider_port
  openvswitch.openvswitch.openvswitch_port:
    bridge: br-provider
    port: "{{ provider_interface }}"

- name: put_neutron_config_templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '644'
  notify: restart_neutron
  loop:
    - { src: './neutron.conf.j2', dest: '/etc/neutron/neutron.conf' }
    - { src: './openvswitch_agent.ini.j2', dest: '/etc/neutron/plugins/ml2/openvswitch_agent.ini' }
