---
- name: install_packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - nova-compute
    - seabios

- name: disable_libvirt_default_network
  community.libvirt.virt_net:
    name: default
    state: absent
    autostart: false

- name: put_nova_config
  ansible.builtin.template:
    src: ./nova.conf.j2
    dest:  /etc/nova/nova.conf
    owner: root
    group: root
    mode: '644'
  notify: restart_nova

- name: install_nova_compute_qemu
  ansible.builtin.apt:
    name: nova-compute-qemu
