---
- name: install_packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - nova-compute
    - seabios

- name: disable_libvirt_default_network
  community.libvirt.virt_net:
    name: default
    state: absent
    autostart: false

- name: put_nova_config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '644'
  notify: restart_nova
  loop:
    - { src: './nova.conf.j2', dest: '/etc/nova/nova.conf' }
    - { src: './nova-compute.conf.j2', dest: '/etc/nova/nova-compute.conf' }
